### ISSUE TITLE
Question about feature of amino acid descriptors

### ISSUE THREAD

**Issue by yang-arina** [songlab-cal/CPT#2]
Hi! I'm going through the feature of amino acid descriptors, and I wonder where does this kind of feature come from? It seems that I have not found relevant information in the article and on the Zenodo website.
`KF1,KF2,KF3,KF4,KF5,KF6,KF7,KF8,KF9,KF10: `
If you could reply as soon as possible, I would be extremely grateful！

**Comment by mjag1898** [comment]
Amino acid descriptor features are sourced from main text references 49-55. For the specific features that were used in the final model, see supplement references 11-13. 

This Github associated with main text reference 49 provides the tables: https://github.com/dosorio/Peptides

**Comment by yang-arina** [comment]
Thank you for your reply! I have identified and understood the sources of all features except for `KF1,KF2,KF3,KF4,KF5,KF6,KF7,KF8,KF9,KF10`, I am unsure are they the `kideraFactors` mentioned in https://github.com/dosorio/Peptides?
![image](https://github.com/songlab-cal/CPT/assets/128577558/e73c2d41-3bb7-44fb-9c7c-1c215c404f03)
